### ISSUE TITLE
Bug: Graph has stopped responding to changes

### ISSUE THREAD

**Issue by armanmoztar** [MLH-Fellowship/prep-project-22.NOV.PREP.2#70]
<img width="838" alt="Screenshot 2022-11-22 at 10 12 09 AM" src="https://user-images.githubusercontent.com/75223820/203390377-51c4f5d5-29fa-4ae2-9c68-88c468237a6a.png">

**Comment by ciradu2204** [comment]
Hi @arman, this is not a bug. Due to the three-hour interval gap, the graph will display the data starting from the nearest hour. Therefore, when you checked it, it was around 21:00pm. The next interval gap would be midnight which belongs to another day(Tuesday). Therefore, the 21:00pm temperature will only be displayed.

**Comment by ciradu2204** [comment]
May be we could discuss another way of displaying it

**Comment by armanmoztar** [comment]
Oh ok thanks for letting me know. I thought it was just something on my end
